language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "WEjn4vvFCiWOucAFtI73u1QnnKsYVsle7xLwKZWzAUpaSdcAhMFUD1Q4OoCsGIqQ5E+D9pdzQ7+qiH1NYhJhxFSCdvIdU63OkvbRKkRozXOQHdO/N392HcbedJ4B7FxC2x8wof3loPaBPcPmEfHYXyZM2JWw6LWHpJEH1xW/OEQ="
    on:
      tags: true
      all_branches: true
